Backup

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -802,6 +802,8 @@ RANLIB
 AR
 ECHO
 LN_S
+APPINDICATOR_LIBS
+APPINDICATOR_CFLAGS
 LIBNOTIFY_LIBS
 LIBNOTIFY_CFLAGS
 SDL3_TTF_LIBS
@@ -916,7 +918,9 @@ SDL3_IMAGE_LIBS
 SDL3_TTF_CFLAGS
 SDL3_TTF_LIBS
 LIBNOTIFY_CFLAGS
-LIBNOTIFY_LIBS'
+LIBNOTIFY_LIBS
+APPINDICATOR_CFLAGS
+APPINDICATOR_LIBS'
 
 
 # Initialize some variables set by options.
@@ -1596,6 +1600,10 @@ Some influential environment variables:
               C compiler flags for LIBNOTIFY, overriding pkg-config
   LIBNOTIFY_LIBS
               linker flags for LIBNOTIFY, overriding pkg-config
+  APPINDICATOR_CFLAGS
+              C compiler flags for APPINDICATOR, overriding pkg-config
+  APPINDICATOR_LIBS
+              linker flags for APPINDICATOR, overriding pkg-config
 
 Use these variables to override the choices made by 'configure' or to help
 it to find libraries and programs with nonstandard names/locations.
@@ -5247,6 +5255,90 @@ printf "%s\n" "#define HAVE_LIBNOTIFY 1" >>confdefs.h
 
 fi
 
+
+pkg_failed=no
+{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for appindicator3-0.1" >&5
+printf %s "checking for appindicator3-0.1... " >&6; }
+
+if test -n "$APPINDICATOR_CFLAGS"; then
+    pkg_cv_APPINDICATOR_CFLAGS="$APPINDICATOR_CFLAGS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"appindicator3-0.1\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "appindicator3-0.1") 2>&5
+  ac_status=$?
+  printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_APPINDICATOR_CFLAGS=`$PKG_CONFIG --cflags "appindicator3-0.1" 2>/dev/null`
+		      test "x$?" != "x0" && pkg_failed=yes
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+if test -n "$APPINDICATOR_LIBS"; then
+    pkg_cv_APPINDICATOR_LIBS="$APPINDICATOR_LIBS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"appindicator3-0.1\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "appindicator3-0.1") 2>&5
+  ac_status=$?
+  printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_APPINDICATOR_LIBS=`$PKG_CONFIG --libs "appindicator3-0.1" 2>/dev/null`
+		      test "x$?" != "x0" && pkg_failed=yes
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+        { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: no" >&5
+printf "%s\n" "no" >&6; }
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        APPINDICATOR_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors --cflags --libs "appindicator3-0.1" 2>&1`
+        else
+	        APPINDICATOR_PKG_ERRORS=`$PKG_CONFIG --print-errors --cflags --libs "appindicator3-0.1" 2>&1`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$APPINDICATOR_PKG_ERRORS" >&5
+
+
+    { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: appindicator3-0.1 not found, tray AppIndicator backend will be disabled" >&5
+printf "%s\n" "$as_me: WARNING: appindicator3-0.1 not found, tray AppIndicator backend will be disabled" >&2;}
+
+elif test $pkg_failed = untried; then
+        { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: no" >&5
+printf "%s\n" "no" >&6; }
+
+    { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: appindicator3-0.1 not found, tray AppIndicator backend will be disabled" >&5
+printf "%s\n" "$as_me: WARNING: appindicator3-0.1 not found, tray AppIndicator backend will be disabled" >&2;}
+
+else
+	APPINDICATOR_CFLAGS=$pkg_cv_APPINDICATOR_CFLAGS
+	APPINDICATOR_LIBS=$pkg_cv_APPINDICATOR_LIBS
+        { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+printf "%s\n" "yes" >&6; }
+
+
+printf "%s\n" "#define HAVE_TRAY_APPINDICATOR 1" >>confdefs.h
+
+    CFLAGS="$CFLAGS $APPINDICATOR_CFLAGS"
+    LDFLAGS="$LDFLAGS $APPINDICATOR_LIBS"
+
+fi
+
   SDL_SOURCE_FILES="sdl3.c helper.c sdl3_image.c sdl3_ttf.c sdl3_events.c"
 
 
@@ -6102,7 +6194,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 6105 "configure"' > conftest.$ac_ext
+  echo '#line 6197 "configure"' > conftest.$ac_ext
   if { { eval echo "\"\$as_me\":${as_lineno-$LINENO}: \"$ac_compile\""; } >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7481,7 +7573,7 @@ else case e in #(
       LDFLAGS="$LDFLAGS -Wl,-exported_symbols_list,conftest.sym"
 
 cat > conftest.$ac_ext <<EOF
-#line 7484 "configure"
+#line 7576 "configure"
 #include "confdefs.h"
 int main(void) {
 ; return 0; }
@@ -7643,11 +7735,11 @@ else case e in #(
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"configure:7646: $lt_compile\"" >&5)
+   (eval echo "\"configure:7738: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "configure:7650: \$? = $ac_status" >&5
+   echo "configure:7742: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7943,11 +8035,11 @@ else case e in #(
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"configure:7946: $lt_compile\"" >&5)
+   (eval echo "\"configure:8038: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "configure:7950: \$? = $ac_status" >&5
+   echo "configure:8042: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8051,11 +8143,11 @@ else case e in #(
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"configure:8054: $lt_compile\"" >&5)
+   (eval echo "\"configure:8146: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "configure:8058: \$? = $ac_status" >&5
+   echo "configure:8150: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -8516,7 +8608,7 @@ _LT_EOF
        # Determine the default libpath from the value encoded in an empty executable.
 
 cat > conftest.$ac_ext <<EOF
-#line 8519 "configure"
+#line 8611 "configure"
 #include "confdefs.h"
 int main(void) {
 ; return 0; }
@@ -8558,7 +8650,7 @@ if test -z "$aix_libpath"; then aix_libpath="/usr/lib:/lib"; fi
 	 # Determine the default libpath from the value encoded in an empty executable.
 
 cat > conftest.$ac_ext <<EOF
-#line 8561 "configure"
+#line 8653 "configure"
 #include "confdefs.h"
 int main(void) {
 ; return 0; }
@@ -10139,7 +10231,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10142 "configure"
+#line 10234 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10238,7 +10330,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10241 "configure"
+#line 10333 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11307,7 +11399,7 @@ case $host_os in
       # Determine the default libpath from the value encoded in an empty executable.
 
 cat > conftest.$ac_ext <<EOF
-#line 11310 "configure"
+#line 11402 "configure"
 #include "confdefs.h"
 int main(void) {
 ; return 0; }
@@ -11350,7 +11442,7 @@ if test -z "$aix_libpath"; then aix_libpath="/usr/lib:/lib"; fi
 	# Determine the default libpath from the value encoded in an empty executable.
 
 cat > conftest.$ac_ext <<EOF
-#line 11353 "configure"
+#line 11445 "configure"
 #include "confdefs.h"
 int main(void) {
 ; return 0; }
@@ -12603,11 +12695,11 @@ else case e in #(
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"configure:12606: $lt_compile\"" >&5)
+   (eval echo "\"configure:12698: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "configure:12610: \$? = $ac_status" >&5
+   echo "configure:12702: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12711,11 +12803,11 @@ else case e in #(
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"configure:12714: $lt_compile\"" >&5)
+   (eval echo "\"configure:12806: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "configure:12718: \$? = $ac_status" >&5
+   echo "configure:12810: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
